# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 4096
CPU = 2

Vagrant.configure("2") do |config|
  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "mrvantage/centos7-minikube"
    minikube.vm.network "private_network", type: "dhcp"
    minikube.vm.hostname = "minikube"
    minikube.vm.synced_folder '.', '/vagrant', disabled: true
    minikube.vm.provider "virtualbox" do |v|
      v.name = "minikube"
      v.memory = RAM
      v.cpus = CPU
    end
  end
end