# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 1024
CPU = 1
IP = "10.0.0.10"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: IP
     config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "nginx.yml"
      ansible.install = true
      ansible.install_mode = "pip"
      ansible.pip_install_cmd = "curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | sudo python"
    end
    config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
    end
end
