# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 2048
CPU = 2

Vagrant.configure("2") do |config|
  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "debian/jessie64"
    minikube.vm.network "private_network", type: "dhcp"
    minikube.vm.hostname = "minikube"
    minikube.vm.provider "virtualbox" do |v|
      v.name = "minikube"
      v.memory = RAM
      v.cpus = CPU
    end
    minikube.vm.provision :shell do |shell|
      shell.path = "minikube.sh"
    end
  end
end
